#include "widget.h"
#include <QApplication>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    a.setFont(QFont("Microsoft Yahei", 10));
    a.setStyleSheet("Widget{"
                    "background:white;"
                    "}"
                    "QPushButton{"
                    "border:0px;"
                    "color:white;"
                    "background:#00BFFF;"
                    "padding:5px 15px;"
                    "}"
                    "QPushButton:hover{"
                    "background:#59D6FF;"
                    "}"
                    "QPushButton:pressed{"
                    "background:#00A3D9;"
                    "}"
                    "QListView{"
                    "border:1px solid #00BFFF;"
                    "outline:0;"
                    "}"
                    "QListView::item{"
                    "border:0px;"
                    "padding:5px 5px;"
                    "}"
                    "QListView::item:hover{"
                    "background:#DEF7FF;"
                    "}"
                    "QListView::item:selected{"
                    "background:#00ACE6;"
                    "color:white;"
                    "}"
                    "Widget QScrollBar:horizontal{"
                    "height:5px;"
                    "background:transparent;"
                    "}"
                    "Widget QScrollBar:vertical{"
                    "width:5px;"
                    "background:transparent;"
                    "}"
                    "Widget QScrollBar::handle{"
                    "background:#0DC2FF;"
                    "}"
                    "Widget QScrollBar::sub-line:vertical,"
                    "Widget QScrollBar::add-line:vertical{"
                    "height:0px;"
                    "}"
                    "Widget QScrollBar::sub-line:horizontal,"
                    "Widget QScrollBar::add-line:horizontal{"
                    "width:0px;"
                    "}"
                    "Widget QScrollBar::sub-line,"
                    "Widget QScrollBar::sub-page{"
                    "}"
                    "Widget QScrollBar::add-line,"
                    "Widget QScrollBar::add-page{"
                    "}"
                    "QAbstractScrollArea::corner{"
                    "background: transparent;"
                    "border: none;"
                    "}"
                    "AnimatedScrollBar{"
                    "qproperty-expandedWidth:15;"
                    "}");
    Widget w;
    w.show();

    return a.exec();
}
